server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:./db_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # ????? ??? ??? ?????. update? ??
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect